### ISSUE TITLE
critical bug in dna to protein code

### ISSUE THREAD

**Issue by rohanmaddamsetti** [prestevez/dna2proteins#2]
There's a bug in your dna_translate code. If a codon is not found in the genetic code dictionary, an 'N' is added to the protein. However, 'N' is a valid amino acid (asparagine'). It is better to set to a gap character '-' or some character that is an invalid amino acid.

Cheers

**Comment by prestevez** [comment]
Hi, this package is not maintained and was developed mostly as an in-class exercise to learn python. I will add a note to the Readme page so that this is clearly indicated. You are free to submit a pull request to incorporate a fix though, and I would very gladly welcome it!

**Comment by prestevez** [comment]
Hi, this package is not maintained and was developed mostly as an in-class exercise to learn python. I will add a note to the Readme page so that this is clearly indicated. You are free to submit a pull request to incorporate a fix though, and I would very gladly welcome it!
