### ISSUE TITLE
Protein translation polycistronic model (All 3 frames and multiple ORF within every frame starting with "M")

### ISSUE THREAD

**Issue by BenSamy2020** [prestevez/dna2proteins#3]
Greetings,

I would like to thank you for providing this open source dna2protein script.

Will there be anyway to edit the script to obtain protein translation using a polycistronic model. I would like to obtain a list of proteins (>30 amino acid) from a single transcript: +1, +2, +3 frames and within each frame multiple ORFs starting with "M".

Based on your provided code, I do not want the option of finding the longest protein in each sequence. I would like to obtain all the protein ORFs that are >30 AA from all reading frames.

I am purely an experimental biologist. Currently, trying to learn my way through coding. I apologise ahead for such newbie questions. 

Lastly, I would like to thank you in advance for your assistances.
*This is not any issue associated with your code,  but more of an add-on feature.

Regards,
Ben

**Comment by prestevez** [comment]
Hi Ben,

Unfortunately this project is not maintained. It was created as part of a Python training, and I am not a biologist so I really wouldn't know how to achieve what you re looking for.

However, the code is MIT licensed, so feel free to fork or clone the repo and modify the code as desired.

Good luck!
